title: Zuhair Abouelkheir
logo: github_picture.JPG
description: Ambitious engineering student actively searching for an internship while exploring various subfields to find my area of interest
show_downloads: true
theme: jekyll-theme-minimal
