title: Zuhair Abouelkheir
logo: github_picture.JPG
description: Aspiring Software and Data Engineer. Currently seeking internships to obtain experience in either field.
show_downloads: true
theme: jekyll-theme-minimal
